# Generated by Django 4.1 on 2023-04-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_user', models.ImageField(blank=True, default='icon_user/default-user-profile-picture.jpg', null=True, upload_to='icon_user', verbose_name='Иконка пользователя')),
                ('rule_user_status', models.CharField(choices=[('0', 'Admin'), ('1', 'Moderator'), ('3', 'User')], default='3', max_length=3, verbose_name='Роль пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
