# Generated by Django 4.1.7 on 2023-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon_user',
            field=models.ImageField(blank=True, null=True, upload_to='icon_user', verbose_name='Icon user'),
        ),
    ]
