# Generated by Django 4.1.7 on 2023-04-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_icon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rule', models.CharField(max_length=50, verbose_name='Роль')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rule_user_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.ruleuser', verbose_name='Роль пользователя'),
        ),
    ]
