# Generated by Django 4.1 on 2023-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel_norm_car',
            name='order_number',
            field=models.TextField(unique=True, verbose_name='Номер приказа'),
        ),
    ]
