# Generated by Django 4.1 on 2023-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0004_alter_cars_options_alter_fuel_norm_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='reg_numb_car',
            field=models.TextField(max_length=10, unique=True, verbose_name='Регистрационные знаки'),
        ),
        migrations.AlterField(
            model_name='fuel_norm_car',
            name='order_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер приказа'),
        ),
    ]
