# Generated by Django 4.1 on 2023-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0005_alter_cars_reg_numb_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='reg_numb_car',
            field=models.CharField(max_length=10, unique=True, verbose_name='Регистрационные знаки'),
        ),
    ]
