# Generated by Django 4.1 on 2023-05-08 13:30

import MyAppProject.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0006_alter_cars_reg_numb_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelsheetslist',
            name='sheets_status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Статус требуется ли пересчитать данные за день'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='status_aprove',
            field=models.BooleanField(default=False, verbose_name='Статус согласования бухгалтером'),
        ),
        migrations.AlterField(
            model_name='fuel_norm_car',
            name='order_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyAppProject.cars', unique_for_date='order_date', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='fuel_norm_car',
            name='order_file',
            field=models.FileField(unique_for_date='order_date', upload_to=MyAppProject.models.Fuel_norm_car.order_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Скан приказа'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_economy',
            field=models.FloatField(default=0, editable=False, verbose_name='Экономия(+) / Перерасход(-)'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_remain_date',
            field=models.FloatField(default=0, editable=False, verbose_name='Остаток топлива'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_used',
            field=models.FloatField(default=0, editable=False, verbose_name='Использовано топлива'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_day_finish',
            field=models.FloatField(default=0, editable=False, verbose_name='Показания одометра на конец дня'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_day_start',
            field=models.FloatField(default=0, editable=False, verbose_name='Показания одометра на начало дня'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='sheets_car',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='MyAppProject.cars', unique_for_date='sheets_date', verbose_name='Автомобиль'),
        ),
    ]
