# Generated by Django 4.1 on 2023-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0007_travelsheetslist_sheets_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelsheetslist',
            old_name='status_aprove',
            new_name='status_approve',
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='used_coefficient_city',
            field=models.BooleanField(default=False, verbose_name='Приминение повышающего коэфициента при передвижении в городе'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='used_coefficient_cold',
            field=models.BooleanField(default=False, verbose_name='Приминение повышающего коэфициента на заморозки'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_economy',
            field=models.FloatField(default=0, verbose_name='Экономия(+) / Перерасход(-)'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_remain_date',
            field=models.FloatField(default=0, verbose_name='Остаток топлива'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='fuel_used',
            field=models.FloatField(default=0, verbose_name='Использовано топлива'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_day_finish',
            field=models.FloatField(default=0, verbose_name='Показания одометра на конец дня'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_day_start',
            field=models.FloatField(default=0, verbose_name='Показания одометра на начало дня'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='sheets_status',
            field=models.BooleanField(default=True, verbose_name='Статус требуется ли пересчитать данные за день'),
        ),
    ]
