# Generated by Django 4.1 on 2023-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0008_rename_status_aprove_travelsheetslist_status_approve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelsheetslist',
            name='fuel_remain_date',
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='fuel_day_fihish',
            field=models.FloatField(default=0, verbose_name='Остаток топлива на конец дня'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='fuel_day_start',
            field=models.FloatField(default=0, verbose_name='Остаток топлива на начало дня'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='fuel_used_actually',
            field=models.FloatField(default=0, verbose_name='Использовано топлива фактически'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='travel_itinerary_finish',
            field=models.TextField(default='', null=True, verbose_name='Маршрут следования куда'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='travel_itinerary_start',
            field=models.TextField(default='', null=True, verbose_name='Маршрут следования откуда'),
        ),
    ]
