# Generated by Django 4.1 on 2023-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0009_remove_travelsheetslist_fuel_remain_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelsheetslist',
            name='used_coefficient_city',
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='odometer_on_day_in_city',
            field=models.FloatField(default=0, verbose_name='пробег по городу'),
        ),
        migrations.AddField(
            model_name='travelsheetslist',
            name='odometer_on_day_out_city',
            field=models.FloatField(default=0, verbose_name='пробег за городом'),
        ),
    ]
