# Generated by Django 4.1 on 2023-05-18 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyAppProject', '0010_remove_travelsheetslist_used_coefficient_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='driver_car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='sheets_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyAppProject.cars', unique_for_date='sheets_date', verbose_name='Автомобиль'),
        ),
    ]
