# Generated by Django 4.1 on 2023-05-28 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0011_alter_cars_driver_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_on_day_in_city',
            field=models.FloatField(default=0, help_text='Введите пробег по городу', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='пробег по городу'),
        ),
        migrations.AlterField(
            model_name='travelsheetslist',
            name='odometer_on_day_out_city',
            field=models.FloatField(default=0, help_text='Введите пробег за городом', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='пробег за городом'),
        ),
    ]
