# Generated by Django 4.1 on 2023-09-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppProject', '0012_alter_travelsheetslist_odometer_on_day_in_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelsheetslist',
            name='sheets_status',
        ),
    ]
