# Generated by Django 4.1.7 on 2023-04-02 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=30, verbose_name='Марка авто')),
                ('reg_numb_car', models.TextField(unique=True, verbose_name='Регистрационные знаки')),
                ('driver_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_norm_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(verbose_name='Номер приказа')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('order_upd', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('order_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('order_file', models.FileField(upload_to=project.models.Fuel_norm_car.order_directory_path, verbose_name='Скан приказа')),
                ('order_fuel', models.CharField(choices=[('80', 'АИ-80'), ('76', 'АИ-76'), ('92', 'АИ-92'), ('95', 'АИ-95'), ('98', 'АИ-98'), ('ДТ', 'ДТ'), (None, 'Марка топлива не указана')], default=None, max_length=5, verbose_name='Марка топлива')),
                ('fuel_consumption', models.FloatField(default=0, verbose_name='Норма расхода топлива')),
                ('order_car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.cars', verbose_name='Автомобиль')),
            ],
        ),
    ]
