# Generated by Django 4.1 on 2023-05-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon_user',
            field=models.ImageField(blank=True, default='icon_user/default-user-icon.jpg', null=True, upload_to='icon_user', verbose_name='Иконка пользователя'),
        ),
    ]
