# Generated by Django 4.1 on 2023-05-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_icon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_approve',
            field=models.DateField(default='2022-12-31', verbose_name='Дата последней пройденной проверки'),
        ),
    ]
