# Generated by Django 4.1.7 on 2023-04-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ruleuser_user_rule_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rule_user_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.ruleuser', verbose_name='Роль пользователя'),
        ),
    ]
